# Generated by Django 4.1.2 on 2022-10-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('partido_id', models.IntegerField(primary_key=True, serialize=False)),
                ('partido_eq1', models.CharField(blank=True, max_length=30, null=True)),
                ('partido_resultado_eq1', models.IntegerField(blank=True, null=True)),
                ('partido_eq2', models.CharField(blank=True, max_length=30, null=True)),
                ('partido_resultado_eq2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'EQUIPOS',
                'managed': False,
            },
        ),
    ]
