# Generated by Django 4.1.2 on 2022-10-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confApp', '0002_resultados_alter_equipos_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipos',
            old_name='partido_resultado_eq1',
            new_name='diferencia_goles',
        ),
        migrations.RenameField(
            model_name='equipos',
            old_name='partido_resultado_eq2',
            new_name='goles_contra',
        ),
        migrations.RenameField(
            model_name='equipos',
            old_name='partido_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='equipos',
            old_name='partido_eq1',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='equipos',
            name='partido_eq2',
        ),
        migrations.AddField(
            model_name='equipos',
            name='goles_favor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipos',
            name='puntos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='equipos',
            table=None,
        ),
        migrations.AlterModelTable(
            name='resultados',
            table='RESULTADOS',
        ),
    ]
